//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ???????????????????????
//     ????????????????
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace WpfDesignAndAnimationLab.Effects {
	
	public class ClipEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ClipEffect), 0);
		public static readonly DependencyProperty BlendProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Blend", typeof(ClipEffect), 1);
		public ClipEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("/WpfDesignAndAnimationLab.Effects;component/Shaders/ClipEffect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(BlendProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public Brush Blend {
			get {
				return ((Brush)(this.GetValue(BlendProperty)));
			}
			set {
				this.SetValue(BlendProperty, value);
			}
		}
	}
}
