//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ???????????????????????
//     ????????????????
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace WpfDesignAndAnimationLab.Effects {
	
	public class MyShadowEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(MyShadowEffect), 0);
		public static readonly DependencyProperty SampleInputParamProperty = DependencyProperty.Register("SampleInputParam", typeof(double), typeof(MyShadowEffect), new UIPropertyMetadata(((double)(3.5D)), PixelShaderConstantCallback(0)));
		public MyShadowEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("/WpfDesignAndAnimationLab.Effects;component/MyShadowEffect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(SampleInputParamProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public double SampleInputParam {
			get {
				return ((double)(this.GetValue(SampleInputParamProperty)));
			}
			set {
				this.SetValue(SampleInputParamProperty, value);
			}
		}
	}
}
