//------------------------------------------------------------------------------
// <auto-generated>
//     ?????????
//     ?????:4.0.30319.42000
//
//     ???????????????????????
//     ????????????????
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace WpfDesignAndAnimationLab.Effects {
	
	public class ThresholdEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ThresholdEffect), 0);
		public static readonly DependencyProperty ThreshProperty = DependencyProperty.Register("Thresh", typeof(double), typeof(ThresholdEffect), new UIPropertyMetadata(((double)(3.5D)), PixelShaderConstantCallback(0)));
		public ThresholdEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("/WpfDesignAndAnimationLab.Effects;component/Shaders/ThresholdEffect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(ThreshProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public double Thresh {
			get {
				return ((double)(this.GetValue(ThreshProperty)));
			}
			set {
				this.SetValue(ThreshProperty, value);
			}
		}
	}
}
